version: '3'

services:
  linux:
    image: sddevelopmentbe/docgen:latest
    stdin_open: true
    working_dir: /root/docGen
    volumes:
      - $PWD/documents:/root/docGen/documents
      - $PWD/docs:/root/docGen/docs
      - $PWD/output:/root/docGen/output
      - $PWD/ops/scripts:/root/docGen/scripts
      - $PWD/ops/templates:/root/docGen/templates
    environment:
      - ALLOW_PLANTUML_INCLUDE=true
  kroki:
    image: yuzutech/kroki
    volumes:
      - $PWD/documents:/root/docGen/documents
      - $PWD/output:/root/docGen/output
      - $PWD/ops/scripts:/root/docGen/scripts
      - $PWD/ops/templates:/root/docGen/templates
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - ALLOW_PLANTUML_INCLUDE=true
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    ports:
      - "8000:8000"
  blockdiag:
    image: yuzutech/kroki-blockdiag
    ports:
      - "8001:8001"
  mermaid:
    image: yuzutech/kroki-mermaid
    ports:
      - "8002:8002"
  bpmn:
    image: yuzutech/kroki-bpmn
    ports:
      - "8003:8003"
  excalidraw:
    image: yuzutech/kroki-excalidraw
    ports:
      - "8004:8004"
  webserver:
    image: httpd:2.4-alpine
    ports:
      - "8099:80"
