name: Documentation Conversion

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Spin up Containers
        run: |
          echo "<(^v^)> -{ Creating docker containers! }"
          docker-compose -f ./ops/docker-compose.yml up -d --remove-orphans
      - name: List Containers
        run: docker ps
      - name: Start Conversion
        run: |
          echo "<(^v^)> - { Using scripts from /root/docGen/scripts/})"
          docker-compose -f ./ops/docker-compose.yml exec -T linux sh /root/docGen/scripts/doc_runner.sh documents/document_sample.md document sdd-base
          docker-compose -f ./ops/docker-compose.yml exec -T linux sh /root/docGen/scripts/slide_runner.sh documents/slidedeck/docGen-slidedeck.md docgen_slides eisvogel
          docker-compose -f ./ops/docker-compose.yml exec -T linux sh /root/docGen/scripts/slide_web_runner.sh documents/slidedeck/docGen-slidedeck.md docgen_slides markdown_github
      - name: Upload Examples
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
