name: Documentation Conversion

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Spin up Containers
        run: |
          echo "<(^v^)> -{ Creating docker containers! }"
          docker-compose -f ./ops/docker-compose.yml up -d --remove-orphans
      - name: List Containers
        run: docker ps
      - name: Start Conversion
        run: |
          echo "<(^v^)> - { Using scripts from /root/docGen/scripts/})"
          sh ./ops/scripts/convert_documents.sh
      - name: Upload Examples
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
      - name: "Copy output to examples"
        run: |
          ./ops/scripts/copy_examples.sh
      - name: "Commit examples"
        uses: EndBug/add-and-commit@v7
        with:
          message: 'GITOPS: add examples after build'
          add: './examples'
