name: Build and publish Docker image
on:
  release:
    types: [published]
  push:
    branches: main
# on:
#   push:
#     branches:
#       - master
jobs:
  push_to_registry:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: tag_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/heads\//}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_GITHUB_ACTIONS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        with:
          context: ./ops/
          file: ./ops/Dockerfile
          push: true
          tags: |
            sddevelopmentbe/docgen:latest
            sddevelopmentbe/docgen:${{ steps.tag_name.outputs.SOURCE_TAG }}
